# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
- development

resources:
  repositories:
    - repository: templates
      type: git
      name: ViCommon.Shared

pool:
  vmImage: ubuntu-latest

variables:
  # change these so they fit the project
  projectPath: $(solutionPath)/ViCommon.Functional
  testProjectPath: $(solutionPath)/ViCommon.Functional.UnitTest
  ignoredWarnings: CS1702|CS1701|\bS[0-9]{3,}
  sonarProjectKey: ViCommon.Functional

  # these should stay the same
  sonarOrganization: vi-sit
  sonarUrl: 'SonarClound'
  solutionPath: $(Build.SourcesDirectory)
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''
  NUGET_PACKAGES : $(Pipeline.Workspace)/.nuget/packages
  branchSourcePath: $(Build.SourceBranch)

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildSolution
    displayName: Build the Solution
    steps:
      - checkout: self
        submodules: true
      - template: Ci/git-version.yml@templates
      - template: Ci/nuget-restore.yml@templates
      - template: Ci/test.yml@templates
      - template: Ci/sonarqube.yml@templates
        parameters:
          buildSteps:
            - template: build.yml # because this is executed in Ci/sonarqube.yml the wokring directory is Ci
      - template: Ci/nuget-publish.yml@templates