name: Build, Test, and Publish

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    release:
        types: [published]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.0.x"

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Test
              run: dotnet test --no-restore --verbosity normal

    publish-nuget:
        needs: build-and-test
        runs-on: ubuntu-latest
        if: github.event_name == 'release'

        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.0.x"

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                  versionSpec: "5.x"

            - name: Determine Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.10.2

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.assemblySemVer }}

            - name: Pack
              run: dotnet pack --configuration Release --no-build --output nupkgs p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}

            - name: Push to NuGet
              run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
